### ISSUE TITLE
WNFS v1 Test Suite

### ISSUE THREAD

**Issue by expede** [fission-codes/webnative#201]

**Comment by bgins** [comment]
Updating on the status of our test suites.

## Completed

### Unit tests and prop checks
- Most of `src/common` is tested with unit tests and prop checks
- A few unit tests of mmpts, paths, and usernames

### Integration tests
- Filesystem tests for appPaths, concurrency, and creating parent directories automatically
- UCAN tests and UCAN permissions for private paths
- Did tests verifying UCAN signatures and converting public keys to DIDs

## Next steps
- Fix broken tests
  + `src/common/cid-log.test.ts` on `bgins/testing`
  + `tests/fs/concurrency.test.ts`
  + warning from `tests/fs/tree.test.ts` that looks like it may be related to DI
- Dependency injection opens up some opportunities using WebCrypto and storage in tests
  + Some tests in `src/common/` could replace mocking with dependency injection
- Optimize `mmpt.test.ts`
  + Currently takes 2 minutes or more to run, and it sometimes times out
- Add more unit tests and prop checks in `src/fs/`

**Comment by expede** [comment]
@bgins since these seem bucket-able, is it worth making this Issue an epic, and breaking those out into their own and linking them back to this one? Or do they all effect each other and can't be cleanly separated?

**Comment by bgins** [comment]
@expede I think we could go epic with this one. They should all be fairly independent.

Would we add these as issues to the `webnative` repo? Perhaps with a "testing" label?

**Comment by expede** [comment]
Okay great! Yeah, a testing label, and reference them from this issue so we can track them from here.

Thanks!!

**Comment by bgins** [comment]
Opened issue https://github.com/fission-suite/webnative/issues/221 to track optimization of `mmpt.test.ts`.

**Comment by bgins** [comment]
Alright, opened a few more issues for the next steps mentioned above.

- Update common tests with DI https://github.com/fission-suite/webnative/issues/223
- Fix broken tests https://github.com/fission-suite/webnative/issues/224
- Add fs unit tests and prop checks https://github.com/fission-suite/webnative/issues/225

**Comment by bgins** [comment]
Pull request https://github.com/fission-suite/webnative/pull/232 resolves #223, where we wanted to update the `src/common/` tests with DI. It also takes care of the broken `cid-log` test mentioned in #224.

The next step here is adding the `fs` tests mentioned in #225.

**Comment by icidasset** [comment]
Closing in favour of upcoming rs-wnfs integration.
