### ISSUE TITLE
identifiers should be namespaced

### ISSUE THREAD

**Issue by icidasset** [fission-codes/webnative#283]
Currently identifiers, which are used for read keys and name filters, aren't namespaced. This makes it impossible to have multiple filesystems loaded at the same time, for example, when you have a temporary filesystem (anonymous/unauthorised user) and a filesystem from a Fission user.

**Comment by matheus23** [comment]
Another way to do achieve this would be to have two keystores under different "storeName"s.

```js
import * as wn from "webnative"
import RSAKeyStore from "keystore-idb/rsa"

wn.keystore.set(new RSAKeyStore({ storeName: "2ndStore" })
```

**Comment by icidasset** [comment]
Oh nice, hadn't thought of that, I'll have to test that out.
