### ISSUE TITLE
Problems with UCAN & read key retrieval during lobby auth

### ISSUE THREAD

**Issue by icidasset** [fission-codes/webnative#346]
```
Trying to retrieve UCAN(s) and readKey(s) from the auth lobby timed out after 10 seconds.
```
Got this error various times when authenticating with apps.
Seems to happen more often when you have multiple apps open?

**Comment by ngeojiajun** [comment]
At my side, i found this error is somehow deterministic in which that the same error will throw again if the authentication is attempted from the same app unless the ipfs worker are killed by restarting my browser in my cases.
