### ISSUE TITLE
WebNative FileSystem docs incorrectly listed on API docs site

### ISSUE THREAD

**Issue by jessmartin** [fission-codes/webnative#380]
# Summary

## Problem

The [WebNative FileSystem API docs](https://webnative.fission.app/classes/_internal_.FileSystem.html) are listed under a misleading `<internal>` heading rather than exposed as a top-level export, making it very difficult to discover and navigate to.

### Impact

Difficult to find the `FileSystem` API docs, making it challenging to use the docs to understand WebNative.

## Solution

Ensure the FileSystem docs are listed as a top-level Export on the docs site.

# Detail

**To Reproduce**
1. Go to https://webnative.fission.app/
2. Look in the "Exports" section on the right sidebar.
3. Click the Export titled `<internal>`.
4. Under Classes, click on `FileSystem`.
5. You're now on the `FileSystem` docs page.

**Expected behavior**
The FileSystem docs should be listed as a top-level Export to enable ease of discovery / navigation.

**Screenshots**
![Screen Shot 2022-05-11 at 3 32 20 PM](https://user-images.githubusercontent.com/27258/167931035-d5074346-7387-43bd-ac94-cfa55a6cb457.png)

**Comment by icidasset** [comment]
Fixed in 0.35
