### ISSUE TITLE
fs.cat permission error on public files

### ISSUE THREAD

**Issue by gotjoshua** [fission-codes/webnative#399]
# Summary with details

I have a file [clearly available](https://1zoom.files.fission.name/p/1zm-test1/color-schemes-test1/Colors/1659714480000_16:48:00.000/1659714481311_4f80923d0fe_b9705a4ee1f) in a public user folder
![Screen Shot 2022-08-06 at 11 55 08 AM](https://user-images.githubusercontent.com/8686454/183246000-66a14611-4d7c-4364-8025-922a5fc059a9.png)

When i try to access it via cat i get this error:
```
Uncaught (in promise) NoPermissionError: 
I don't have the necessary permissions to query the file system at 
"public,1zm-test1,color-schemes-test1,
links,1zoom_Colors,
1659714480000_16:48:00.000,1659714481311_4f80923d0fe_b9705a4ee1f"
```
note1: [links,1zoom_Colors,] is a wnfs symlink to:
https://1zoom.files.fission.name/p/1zm-test1/color-schemes-test1/Colors/

note2: I can `ls` the folder just fine (thats how i get the filename to try the `cat` command

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.15.7]
 - Browser [e.g. chromium]

**Comment by icidasset** [comment]
What does your `permissions` object look like that you pass to `initialise`?

**Comment by gotjoshua** [comment]
> What does your `permissions` object look like

```ts
const suffix = '-test3'
export const appNameObj = {
  name: `color-schemes${suffix}`,
  creator: `1zm${suffix}`,
}

  const publicDirectoryArray = [
    wn.path.directory(appNameObj.creator, appNameObj.name), 
    wn.path.directory(appNameObj.creator, appNameObj.name, 'links')
  ]

  state = await wn.initialise({ 
    permissions: {
      app: appNameObj,
      fs: { // Ask the user permission for additional filesystem paths
        public: publicDirectoryArray,
      },
    },
  })
```

not sure if it makes much sense to continue this line of inquiry until after your big upgrade is released...

but... I think the permissions object _should_ be completely irrelevant if i am querying a public path
ls and exists and cat should all be easy to use for all users public paths, independent of any permissions.

**Comment by icidasset** [comment]
We chose this route so the user can easily see when authorising an app which files an app will touch. But yes, you're right, for reading we might need to change that, since it's public anyway.

Does this work when you request permissions for the entire public directory?

**Comment by icidasset** [comment]
Which you would do in the following way:
```js
permissions: {
  fs: {
    public: [ wn.path.root() ]
  }
}
```

**Comment by gotjoshua** [comment]
> Does this work when you request permissions for the entire public directory?

I'll need to check later... neck deep in other stuff and no longer interested in using cat with single files as the car file strategy for the whole file is sooooo much faster.
