### ISSUE TITLE
Faster response time for auth lobby 

### ISSUE THREAD

**Issue by gotjoshua** [fission-codes/webnative#400]
# Summary
![v2AuthLobbyHugeDelay](https://user-images.githubusercontent.com/8686454/183372549-8649ae66-747b-4abf-ba1c-7c45ed44f22e.png)

## Problem

There is a consistent delay during the call to  `await wn.initialise(...`
My refreshes ranged from 180ms to 600ms (most often at the high end of that range) for that green bar "waiting for server response" and it seems that the file is never a cache hit.

### Impact

getting app load under one second is extremely difficult if the core auth library takes half a second to load.

## Solution

Find a better way to serve that tiny v2.html file (i think actually a blob url would be clever)

**Comment by icidasset** [comment]
The `v2.html` is the IPFS worker, this is going away very soon.

**Comment by gotjoshua** [comment]
> this is going away very soon.

bye bye!
