### ISSUE TITLE
Improve read key management and errors

### ISSUE THREAD

**Issue by icidasset** [fission-codes/webnative#418]
When you try to load an existing filesystem and don't have a `readKey` set in the "webnative storage" (aka. localforage indexeddb in the browser), you'll get the error message `Could not parse a valid private tree using the given key`, which can be confusing. The reason for this is because webnative generates a read key on demand, so you'll actually be using the wrong key in this scenario.

It's probably also confusing that you'll also need to call `wn.lobby.storeRootKey` for the filesystem to actually be able to use the filesystem. It might be better to only store in the web crypto api, and make it extractable when needed?

Linking or delegating transfers this read key from one secure context to another.

**Comment by Mayank-sudo** [comment]
i think problem in somewhere in readkey or webnative storage or mabe while pase a validd tree using given key expire on time
