### ISSUE TITLE
Data root missing when linking a second device

### ISSUE THREAD

**Issue by bgins** [fission-codes/webnative#420]
# Summary

## Problem

When a user links their account on a second device immediately after registering, the data root for their filesystem might not be available.

### Impact

The linked device may not be able to load the filesystem right away. The linked device will need to poll until the data root is available.

## Solution

One possibility would be moving the necessary polling into the account linking code. This option is not ideal because we should keep the account linking code decoupled from filesystem concerns.

Another possibility would be to move the polling into `loadFilesystem`: https://github.com/fission-codes/webnative/blob/01b57e2d6616631b2b4a484a46fd14e385aa8a0b/src/filesystem.ts#L35-L103

# Detail

**Describe the bug**

**To Reproduce**
1. Comment out https://github.com/fission-codes/webnative-app-template/blob/05b70fd1596c89204a45a54f4eef81aed45c41ba/src/lib/common/webnative.ts#L111 in the [Webnative app template](https://github.com/fission-codes/webnative-app-template)
2. Register a new user
3. Follow the linking flow
4. The filesystem should fail to load and a `Could not decode CID: undefined` error will appear in the console

**Expected behavior**

The filesystem should load without throwing an exception.

**Screenshots**

The decode CID exception looks like

![decode-cid](https://user-images.githubusercontent.com/7957636/188922122-30b86a70-27be-4a7c-b623-c8dfd492d9c0.png)

Note that the exception is not a direct representation of the missing data root. It occurs because no data root exists and we instead look for a root CID in the CID log, which does not exist yet.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome, Firefox, Safari

**Additional context**

The Webnative app template works around this issue by polling the data root: https://github.com/fission-codes/webnative-app-template/blob/05b70fd1596c89204a45a54f4eef81aed45c41ba/src/lib/common/webnative.ts#L126-L149

**Comment by icidasset** [comment]
I was also looking at this error message earlier today, we're actually calling `decodeCID` at the wrong time.
That line the error points to in `loadFileSystem` should be something like:
```ts
// No DNS CID yet
cid = await cidLog.newest()
cid = cid ? decodeCID(cid) : null
```

**Comment by icidasset** [comment]
I should also point out that if the `loadFileSystem` function worked as it should (ie. with the above fix), it would create a new file system in this situation. Which is obviously also not the correct thing to do.

That said, we could reuse `waitForRootDid` from the channel code here.

**Comment by bgins** [comment]
> I should also point out that if the `loadFileSystem` function worked as it should (ie. with the above fix), it would create a new file system in this situation. Which is obviously also not the correct thing to do.

Yep, agreed. 💯 

> That said, we could reuse `waitForRootDid` from the channel code here.

Would we want to poll the data root instead of the root DID? We are checking the data root in the workaround in the Webnative app template. Would root DID also work?

**Comment by icidasset** [comment]
> Would we want to poll the data root instead of the root DID? We are checking the data root in the workaround in the Webnative app template. Would root DID also work?

Sorry should've been more clear. I meant reusing the retry mechanism of that function, we can easily swap out the DID lookup with the data root lookup.

**Comment by bgins** [comment]
> Sorry should've been more clear. I meant reusing the retry mechanism of that function, we can easily swap out the DID lookup with the data root lookup.

Yep, I think this is the right way to go. I'll implement it and put in a PR with it. 👌
