### ISSUE TITLE
`wn.initialise` throws error

### ISSUE THREAD

**Issue by nichoth** [fission-codes/webnative#423]
# Summary
This example is taken from https://github.com/nichoth/hermes/blob/two/src/index.tsx#L24 . 

This example is based on a working demo — https://github.com/nichoth/fsn/blob/main/src/index.tsx#L13

A change that would explain the difference in API is that the `fsn` demo uses an older version of wnfs. But when I look at [the docs for `path`](https://webnative.fission.app/modules/path.html#directory-1), it seems like that function should be the same

## Problem

```
abstract-level.js:746 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at node_modules/abstract-level/abstract-level.js (abstract-level.js:746:4)
    at __require2 (chunk-S5KM4IGW.js?v=702c219f:18:50)
    at node_modules/abstract-level/index.js (index.js:3:25)
    at __require2 (chunk-S5KM4IGW.js?v=702c219f:18:50)
    at node_modules/browser-level/index.js (index.js:5:27)
    at __require2 (chunk-S5KM4IGW.js?v=702c219f:18:50)
    at node_modules/level/browser.js (browser.js:1:17)
    at __require2 (chunk-S5KM4IGW.js?v=702c219f:18:50)
    at index.js:7:23
```

### Impact
Can't create a wnfs

## Solution

Either update docs with a replacement, or patch the module so that this doesn't throw any more.

**To Reproduce**
1. clone [hermes](https://github.com/nichoth/hermes/blob/two/src/index.tsx#L24)
2. checkout branch `two`
3. type `npm start`

**Screenshots**

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/5776508/190843162-006bd840-2d03-4bd2-b4b3-93dbd952ba52.png">

**Desktop (please complete the following information):**
 - OS -- Mac OS Monterey 12.5.1
 - Browser -- chrome
 - Version [e.g. 22] -- ^0.34.1

**Comment by nichoth** [comment]
I think actually it is `wn.initialize` that is causing the error https://github.com/nichoth/hermes/blob/three/src/index.tsx#L30

**Comment by icidasset** [comment]
@nichoth You have to `npm install events`, we forgot to update the guide. More info here: https://github.com/fission-codes/webnative/pull/410#issue-1344671644

**Comment by nichoth** [comment]
It works now! thanks
