### ISSUE TITLE
Add Filesystem Recovery

### ISSUE THREAD

**Issue by bgins** [fission-codes/webnative#427]
# Summary

## Problem

Account recovery is possible through Dashboard and re-linking the Auth Lobby, but is not available directly from Webnative.

### Impact

Apps that use app-owned auth do not have a recovery mechanism.

## Solution

As a first baseline, let's implement filesystem recovery in Webnative. 

Note that this form of recovery only needs to recover private files and assign the filesystem to a new user. Full account recovery updates the user's account with a new DID by relying on email challenge to authenticate the user. We would like to support full account recovery eventually, but as a first pass we will only need filesystem recovery.

# Detail

**Describe alternatives you've considered**

We've considered full account recovery, but the [Webnative app template](https://github.com/webnative-examples/webnative-app-template) does not collect emails. A future version may include the full email loop, but for now we will only implement filesystem recovery where a user has their username and read key available in a recovery kit.

**Comment by bgins** [comment]
One thing that should be explored here is how much of the recovery process should happen in Webnative and what should be handled by the app. For example, the app should probably create and parse recovery kits. Webnative should validate the contents of the recovery kit and prepare the filesystem.

Not clear where registering a new user and assigning them the filesystem should take place.

**Comment by icidasset** [comment]
Related to #427

**Comment by matheus23** [comment]
@icidasset you perhaps wanted to link another issue, right? You've just linked to the same issue :)

**Comment by icidasset** [comment]
@matheus23 Whoops, thanks 🤣 I meant #304
