### ISSUE TITLE
Failing websocket connections inside Electron

### ISSUE THREAD

**Issue by tennox** [fission-codes/webnative#436]
# Summary

We're trying to run webnative in an Electron app (Logseq Plugin, actually), and we've run into some issues:
- console spamming with WebSocket errors 
- webnative `fs` calls stuck (account linking works, & we get a session)

Both are non-existent for the same app in the web browser.

I talked with @icidasset [on the discord already](https://discord.com/channels/478735028319158273/790825713094754364/1049972424663388160) (+ [the thread we started there](https://discord.com/channels/478735028319158273/1050008800666587237)), and he asked me to summarize this into an issue, so here we are.

I think it might be two separate issues, but they might also be related.

### webnative call
The webnative stuck problem might be caused by the initial websocket connections failing, which might (?) also cause the other problems to appear...
![image](https://user-images.githubusercontent.com/2084639/206223157-b7acff5b-a58d-42ae-a04f-0b0e0e5823d5.png)

But some connections are definitely successful:
![image](https://user-images.githubusercontent.com/2084639/206223267-037e8cbe-14dc-40f0-b756-57eb5a8daf99.png)

### Websocket connection errors

First apparent problem is that the console is (after some seconds) spammed with WebSocket errors:
![image](https://user-images.githubusercontent.com/2084639/206218417-1e66ee31-12c0-408b-801b-71a8fd666a79.png)
(and a never-ending lot of them)

Most of them actually try to connect to localhost, which is weird enough.
I spend a few hours debugging, and seems like this mostly seems to happen because of libp2p `closestPeer` dht stuff, as that was often initiating the connection
![image](https://user-images.githubusercontent.com/2084639/206227879-1ce9cef5-b9c3-4839-a061-3e4b189e06a2.png)

and I found that the peerStore.addressBook listed also the localhost addresses for the fission nodes:
![image](https://user-images.githubusercontent.com/2084639/206227545-4c4b35ca-3e2c-4924-8e5f-425207c5146b.png)

Not really sure if this is just normal with IPFS, and I found that also for the orbitdb demo there where some websocket localhost errors, albeit only two of them and also not continuously spamming...

### ~~We can't use Webnative functions:~~
Actually, after hours of researching and debugging, suddly webnative calls work and I have no idea why.

## Solution

Probably fixing `js-ipfs` - or replacing it, when `pomegranate` or `car-mirror` will be ready :stuck_out_tongue_closed_eyes: 

The webnative issue seems to have resolved, but I will update this issue in case it did not.

# Detail

**To Reproduce**
I tried to make this reproducible, but it was too complex, so for now only works on my machine...

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Browser: [Electron](https://github.com/logseq/logseq/)

**Webnative:**
 - Commit 3bd09cdd70d24d6df32cf9630d6565b9b2beff5b

**Additional context**
I wouldn't initially have put this convoluted mess in an issue report, but I was asked to do so I guess to be able to keep track of UX issues :tipping_hand_man:

**Comment by icidasset** [comment]
Closing in favour of #468
