### ISSUE TITLE
previousCid -> previousCids()[0]

### ISSUE THREAD

**Issue by gotjoshua** [fission-codes/webnative#438]
# Summary
My linter and build chain complain about [this line](https://github.com/fission-codes/webnative/blob/db89623bbab458ccfdfa673b5e0804e36a1e3e7a/src/fs/v3/PublicRootWasm.ts#L439)

## Problem

![image](https://user-images.githubusercontent.com/8686454/206424017-c7a26f44-6ffa-4fa2-91ea-65a6dc819647.png)

### Impact

build fails

## Solution
fix is easy previousCids()[0]
but not sure if that has side effects that you may need to consider.

**Comment by matheus23** [comment]
Fascinating. Did we upgrade the `wnfs` npm library at some point @icidasset?

But yeah. We should fix this.

**Comment by icidasset** [comment]
> Fascinating. Did we upgrade the `wnfs` npm library at some point @icidasset?

Hmm, maybe in the switch from yarn to npm. Does it need to be set to a specific version?

**Comment by matheus23** [comment]
> Hmm, maybe in the switch from yarn to npm. Does it need to be set to a specific version?

Yeah. The API changed between versions. We could just upgrade it though :)

**Comment by icidasset** [comment]
Has the API changed a lot, otherwise I'd change it in the next release. What was the version before, `0.1.7`?

**Comment by matheus23** [comment]
I think it was 0.1.6.
I'm pretty sure the only change to the public API was having multiple previous CIDs per public node. That's all. So I'd recommend just fixing it :)

(Also, the current version of rs-wnfs is 0.1.10. We could look at upgrading to that version while we're at it)

**Comment by matheus23** [comment]
Ah well, perhaps there was also some changes to how `metadata` worked, not sure. So perhaps not *super* easy, but still not hard to do.

**Comment by icidasset** [comment]
I'll keep it to 0.1.6 for now then. Will be working on the upgrade for webnative v0.36 asap after the 0.35 release + private fs integration 👀

**Comment by matheus23** [comment]
Actually, that's incorrect. The previous version was 0.1.7-alpha5.
I think we should just fix this type error and keep it at 0.1.7 for now. The metadata changes are 0.1.8+ I think
