### ISSUE TITLE
Unique usernames per app currently don't work

### ISSUE THREAD

**Issue by bmann** [fission-codes/webnative#462]
A person can register "boris" for the same app / domain (eg webnative-template.fission.app) from any device. 

This is because the hash function includes the DID, which is unique per device. 

We need to document and correct the hash function and goals.

As I understand it, this looks like "boris" + "example.com" to generate a subdomain like HASHNAME.fission.name. 

Then for future registrations the HASHNAME is computed locally and DNS subdomain is checked to see if it exists or not.

**Comment by icidasset** [comment]
Moved to the app template, as there's no username strategy in Webnative as of yet: https://github.com/webnative-examples/webnative-app-template/issues/118
