### ISSUE TITLE
Issue with history.list() from directory and file

### ISSUE THREAD

**Issue by ha6755ad** [fission-codes/webnative#471]
# Summary

## Problem

Cannot list a file or directory history due to the `list` function looking to encode `node.key` as a base64 string as a utf-8 array, but `node.key` is already a utf-8 array. 

### Impact

I believe this makes you entirely unable to list the history for a file or directory - at least in the private directory. 

## Solution

I don't know what the functional intent of having node.key be a Uint8Array, but it seems this would need to be converted to a base64 string - or possibly that is unnecessary and the `fromString` function can be removed from the code.

# Detail

**Describe the bug**

When you call `history.list()` for a file or directory, an error is produced from the file at `src/fs/v1/PrivateHistory` code line `const key = Uint8arrays.fromString(this.node.key, "base64pad");`

This occurs because the node.key is in-fact a Uint8Array. It produces the error `SyntaxError: Non-base64pad character`

**To Reproduce**
`fs.get()` any file or directory and run await `[node].history.list()`

**Expected behavior**
A lovely list of the file/directory history

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by icidasset** [comment]
Should be fixed in the next release v0.36
I'll keep this open until it is released, which should be hopefully next week.

**Comment by icidasset** [comment]
v0.36 is released
