### ISSUE TITLE
mv function not publishing

### ISSUE THREAD

**Issue by ha6755ad** [fission-codes/webnative#480]
# Summary

Inability to publish the results of moving a file or directory

## Problem

The `fs.mv` function is returning the proper filesystem result from its promise, but the result cannot be published successfully. 

### Impact

`mv` is rendered ineffective. 

## Solution

No error is produced, so knowing exactly what the a likely fix is would be hard for me to say. Something to do with refactoring the trees for old and new parent directories a file or directory is moved into - I'm not familiar with what exactly this entails. 

# Detail

**Describe the bug**

**To Reproduce**
Please see example project here for reproducible error https://github.com/bgins/webnative-fs-mv-test

**Expected behavior**
It is expected that `fs.mv` and then `publish` would produce updated persistent directory trees for the affected directories. Again, worth noting is that the `mv` method does return the correct filesystem response, but it is reverted when trying to `publish`. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by icidasset** [comment]
Fix will be in version 0.36, releasing later today.
