### ISSUE TITLE
Soft links to other users' trees cannot be created with `fs.symlink`

### ISSUE THREAD

**Issue by QuinnWilton** [fission-codes/webnative#489]
# Summary

## Problem

The [docs](https://guide.fission.codes/developers/webnative/sharing-private-data#soft-links) suggest that soft links pointed at other users' trees can be created, however the [function itself](https://github.com/fission-codes/webnative/blob/main/src/fs/filesystem.ts#L457) does not take `username` as an argument, and instead just uses the current user.

## Solution

Support passing in an optional `username`, defaulting to the current user. I've hacked up roughly this locally, and it seems to work as intended.

**Comment by icidasset** [comment]
Fixed in version 0.36.2 @QuinnWilton https://webnative.fission.app/classes/FileSystem.html#symlink `referringTo` option of `symlink` now takes an object with an optional username.
