### ISSUE TITLE
Add functions for all API endpoints

### ISSUE THREAD

**Issue by icidasset** [fission-codes/webnative#80]
We're deprecating https://github.com/fission-suite/typescript-client/ and moving most of that here.

Notes:
- I don't think we need to support the legacy username/password stuff here.
- Same thing for all the other deprecated things (correct me if I'm wrong)

## Already implemented

- [x] Create user account with DID & UCAN (`sdk.lobby.createAccount`, `lobby/index.ts`)
- [x] Update user data root (`sdk.dataRoot.update`, `data-root/index.ts`)

### Apps

I would add this under `sdk.apps`

- [x] `GET /app` ☞ `sdk.apps.index`
- [x] `POST /app` ☞ `sdk.apps.create`
- [ ] `PATCH /app/{App URL}/{New CID}` ☞ `sdk.apps.setContent`
- [x] `DELETE /app/associated/{url}` ☞ `sdk.apps.deleteByUrl`
- [ ] `DELETE /app/{appId}` ☞ `sdk.apps.deleteById`

### User

- [ ] `GET /user/whoami` ☞ `sdk.lobby.whoami` or `sdk.lobby.lookupUsername` (not sure which)
- [ ] `PATCH /user/did` ☞ `sdk.did.update`
- [ ] `PUT /user/exchange/keys/{did}` ☞ `sdk.exchange.addPublicKey` (not a 100 on this)
- [ ] `DELETE /user/exchange/keys/{did}` ☞ `sdk.exchange.removePublicKey` (not a 100 on this)

**Comment by expede** [comment]
@walkah can you pease check if the above checklist is current?
